const list = [
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/2918581?v=4",
    forks_count: 67442,
    full_name: "twbs/bootstrap",
    watchers_count: 136972,
    login: "twbs",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/7661012?v=4",
    forks_count: 34565,
    full_name: "nightscout/cgm-remote-monitor",
    watchers_count: 1005,
    login: "nightscout",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/139426?v=4",
    forks_count: 28858,
    full_name: "angular/angular.js",
    watchers_count: 59617,
    login: "angular",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/69631?v=4",
    forks_count: 26596,
    full_name: "facebook/react",
    watchers_count: 139762,
    login: "facebook",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/1916665?v=4",
    forks_count: 24255,
    full_name: "udacity/frontend-nanodegree-resume",
    watchers_count: 1064,
    login: "udacity",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/9892522?v=4",
    forks_count: 23145,
    full_name: "freeCodeCamp/freeCodeCamp",
    watchers_count: 306368,
    login: "freeCodeCamp",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars1.githubusercontent.com/u/6128107?v=4",
    forks_count: 22769,
    full_name: "vuejs/vue",
    watchers_count: 152602,
    login: "vuejs",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars1.githubusercontent.com/u/1562726?v=4",
    forks_count: 21561,
    full_name: "d3/d3",
    watchers_count: 88668,
    login: "d3",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars1.githubusercontent.com/u/70142?v=4",
    forks_count: 18757,
    full_name: "jquery/jquery",
    watchers_count: 52562,
    login: "jquery",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/69631?v=4",
    forks_count: 18529,
    full_name: "facebook/react-native",
    watchers_count: 82777,
    login: "facebook",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/698437?v=4",
    forks_count: 17567,
    full_name: "airbnb/javascript",
    watchers_count: 90623,
    login: "airbnb",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/69631?v=4",
    forks_count: 17262,
    full_name: "facebook/create-react-app",
    watchers_count: 73579,
    login: "facebook",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/629429?v=4",
    forks_count: 14303,
    full_name: "hakimel/reveal.js",
    watchers_count: 49233,
    login: "hakimel",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/1733746?v=4",
    forks_count: 13625,
    full_name: "tastejs/todomvc",
    watchers_count: 26011,
    login: "tastejs",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/1089146?v=4",
    forks_count: 13358,
    full_name: "atom/atom",
    watchers_count: 50460,
    login: "atom",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/39128121?v=4",
    forks_count: 13127,
    full_name: "ColorlibHQ/AdminLTE",
    watchers_count: 32073,
    login: "ColorlibHQ",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/33663932?v=4",
    forks_count: 13079,
    full_name: "mui-org/material-ui",
    watchers_count: 52346,
    login: "mui-org",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/47359?v=4",
    forks_count: 12000,
    full_name: "apache/incubator-echarts",
    watchers_count: 37921,
    login: "apache",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/1136800?v=4",
    forks_count: 10434,
    full_name: "h5bp/html5-boilerplate",
    watchers_count: 43654,
    login: "h5bp",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/1505683?v=4",
    forks_count: 10391,
    full_name: "FortAwesome/Font-Awesome",
    watchers_count: 61439,
    login: "FortAwesome",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars1.githubusercontent.com/u/1333608?v=4",
    forks_count: 9321,
    full_name: "bettiolo/node-echo",
    watchers_count: 11,
    login: "bettiolo",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/3000285?v=4",
    forks_count: 8942,
    full_name: "trekhleb/javascript-algorithms",
    watchers_count: 56374,
    login: "trekhleb",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/10566080?v=4",
    forks_count: 8785,
    full_name: "socketio/socket.io",
    watchers_count: 48071,
    login: "socketio",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/13966722?v=4",
    forks_count: 8174,
    full_name: "hasura/imad-app",
    watchers_count: 15,
    login: "hasura",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/999588?v=4",
    forks_count: 7965,
    full_name: "nolimits4web/swiper",
    watchers_count: 21813,
    login: "nolimits4web",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars1.githubusercontent.com/u/11823761?v=4",
    forks_count: 7831,
    full_name: "ReactTraining/react-router",
    watchers_count: 38387,
    login: "ReactTraining",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars2.githubusercontent.com/u/5658226?v=4",
    forks_count: 7752,
    full_name: "expressjs/express",
    watchers_count: 46239,
    login: "expressjs",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/905434?v=4",
    forks_count: 7668,
    full_name: "ruanyf/es6tutorial",
    watchers_count: 17207,
    login: "ruanyf",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars3.githubusercontent.com/u/139426?v=4",
    forks_count: 7377,
    full_name: "angular/angular-seed",
    watchers_count: 13373,
    login: "angular",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
  {
    avatar_url: "https://avatars0.githubusercontent.com/u/425687?v=4",
    forks_count: 7372,
    full_name: "adam-p/markdown-here",
    watchers_count: 42039,
    login: "adam-p",
    pullRequest: parseInt(Math.random() * 100),
    followers: parseInt(Math.random() * 100),
    following: parseInt(Math.random() * 100),
  },
]

export default list;